### ISSUE TITLE
Creating meeting

### ISSUE THREAD

**Issue by Studentfr** [Alemkhan/beside_me#10]
Some problems with creating meetings because of the meeting serializer, serializer.is_valid method always false

https://github.com/Alemkhan/beside_me/blob/597113409663cf9e211013c96dbd8ce33595a1bc/mainapp/views.py#L87

**Comment by Alemkhan** [comment]
Hope to solve it!

**Comment by Studentfr** [comment]
Solved by creating additional meeting creation serializer
